"""Mirror, tag, compile, gate. Safe to re-run; incremental with an API key."""

import time

from . import mirror
from .gate import baseline_files, describe_baseline, gate, stale
from .source import KEYLESS_MISSING, api_key, fetch_rules, load_tag_config


def sync(
    settings,
    paths,
    full=False,
    limit=None,
    log=print,
    meta_only=False,
    on_rules=None,
):
    """Run a full sync cycle.

    `on_rules` is the seam for embedding this in a larger tool: it is called
    once with `{uuid: metadata row}` for everything fetched, and is where a host
    application indexes rule provenance into its own store. Leave it None and
    the metadata lives only in the sidecar and the rule files.

    `meta_only` fetches every rule and stores its metadata without touching the
    rule files -- the backfill for a mirror synced before metadata existed. It
    ignores the last-sync date by definition, since the rules it describes are
    the old ones.
    """
    keyless = not api_key(settings)
    if keyless:
        # Not a warning about the *number* of requests -- about the columns that
        # simply are not in a public response. Nothing errors; the tags just
        # never appear, which is the kind of gap you find six months later.
        log("no API key: " + "; ".join(sorted(KEYLESS_MISSING.values())))
        if meta_only:
            # Not refused: deleting the cached regex table and re-deriving tags
            # from a newer one is a real reason to run this keyless. But the
            # fields people usually reach for --meta-only to backfill are
            # exactly the ones a public response does not carry, and a keyless
            # run costs the full ~1300-request crawl to change nothing.
            log(
                "  --meta-only keyless re-derives tags from the local regex "
                "table only; the fields above stay absent"
            )
        if settings.get("allow_licenses"):
            raise ValueError(
                "allow_licenses is set, but the public endpoint does not return "
                "a rule's license, so every rule would be skipped and the mirror "
                "would come out empty. Set RULEZET_API_KEY, or clear "
                "allow_licenses to mirror everything."
            )

    paths["root"].mkdir(parents=True, exist_ok=True)
    state = {} if (full or meta_only) else mirror.read_state(paths)

    t0 = time.time()
    rules = fetch_rules(settings, since=state.get("last_sync"), limit=limit, log=log)
    log(f"fetched {len(rules)} rules in {time.time() - t0:.0f}s")
    if not rules:
        log("nothing new.")
        return {}

    tag_config = load_tag_config(paths["tag_config"], log=log)
    tags, rows = mirror.write_rules(
        rules, tag_config, paths, settings, log=log, write_files=not meta_only
    )
    mirror.merge_tags(tags, paths)
    if on_rules:
        on_rules(rows)

    if meta_only:
        log(f"meta-only sync done in {time.time() - t0:.0f}s")
        return rows

    compiled = mirror.compile_mirror(paths, log=log)
    if gate(compiled, paths, settings, log=log):
        # Quarantined rules are gone from the directory but still in the
        # compiled ruleset, so it has to be rebuilt from what survived.
        mirror.compile_mirror(paths, log=log, validate=False)

    n_stale = len(stale(paths, settings))
    if n_stale:
        # Never rechecked automatically: a sync must not silently reopen
        # decisions someone reviewed.
        log(
            f"  {n_stale} quarantined rules are stale "
            f"(run `rulezet-validate mirror recheck`)"
        )

    mirror.write_state(
        paths,
        last_sync=time.strftime("%Y-%m-%d %H:%M"),
        baseline=describe_baseline(baseline_files(settings), settings),
    )
    paths["readme"].write_text(
        "# Synced from rulezet.org\n\n"
        f"Last sync: {time.strftime('%Y-%m-%d %H:%M')}\n"
        f"Rules: {len(list(paths['rules'].glob('*.yara')))} "
        f"(+{len(list(paths['quarantine'].glob('*.yara')))} quarantined)\n\n"
        "Build artifacts, not source: regenerated by `rulezet-validate mirror\n"
        "sync`, never committed. Rule licenses vary per rule -- see the\n"
        "`allow_licenses` setting. `platform_tag_configs.json` is downloaded\n"
        "from rulezet-core (AGPL-3.0) and is deliberately not vendored.\n"
    )
    log(f"sync done in {time.time() - t0:.0f}s")
    return rows
